server:
  port: 8083
#  servlet:
#    context-path: /storage
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      #If you are running your Spring Boot application as a packaged JAR, using a path relative to src/main/resources is not recommended for file uploads because it is not writable. Use a path outside of resources or a path defined by a system property.
  application:
    name: da-storage
    client-id:  2b7f4d5e-8c12-4f8d-b321-6e1d9e9b5f72
    client-secret: Ieoaqb0FtguXpuQUXjESE7PUsVxCkXtq
    upload-folder:
      public: upload/public
      private: upload/private

    valid-extensions: ".txt|.jpg|.png|.docx|.pdf|.zip|.csv|.xlsx|.xls"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: postgres
    password: secret
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uris:
            sso: ${JWK_SSO_URL:http://localhost:8082/realms/master/protocol/openid-connect/certs}
            internal: ${JWK_INTERNAL_URL:http://localhost:8080/auth/certificate/.well-known/jwks.json}

  cloud:
    openfeign:
      circuitbreaker:
        group:
          enabled: true
#resilience4j:
#  circuitbreaker:
#    instances:
#      IamClient:
#        minimumNumberOfCalls: 69
#  timelimiter:
#    instances:
#      IamClient:
#        timeoutDuration: 10s
management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      HttpBinClient_getBinWithDelayInSeconds_int:
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
  timelimiter:
    configs:
      default:
        timeoutDuration: 20s

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

logging:
  level:
    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    io.github.resilience4j: DEBUG