server:
  port: 8762

spring:
  application:
    name: da-gateway

  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true # Enables dynamic routing based on service discovery
      routes:
        #spring.cloud.gateway.routes[1] indicate that route start from index 0
        # uri must be same in eureka application column
        # chú ý không duoc dung '_' tren eureka
        #request url start from Path -> uri -> eureka match uri to Application column -> that service
        - id: da-iam
          uri: lb://DA-IAM
          predicates:
            - Path=/iam/**
          filters:
            - StripPrefix=1
        - id: da-storage
          uri: lb://DA-STORAGE
          predicates:
            - Path=/storage/**
          filters:
#            - Retry=5
#            - name: Retry #This is prebuilt GatewayFilterFactory(https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-retry-gatewayfilter-factory)
#              args:
#                retries: 0
#                statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY,SERVICE_UNAVAILABLE, REQUEST_TIMEOUT #, METHOD_NOT_ALLOWED
#                methods: GET,POST,DELETE
#                exceptions:
#                  - java.io.IOException
#                  - org.springframework.cloud.gateway.support.TimeoutException
#                  - java.lang.UnsupportedOperationException
#                backoff:
#                  firstBackoff: 3s
#                  maxBackoff: 10s
#                  factor: 3
#                  basedOnPreviousValue: false
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                propagate-exceptions: true
                #The fallback mechanism forwards the request exactly as it was originally received (method, headers, body, etc.), except for the target URI.
                #Since gateway only support GetMapping /fallback, the request to /fallback will be Post method that why it cause 405
                fallBackUri: forward:/fallback  #forward doesnt need eureka instance
            - StripPrefix=1
        - id: da-gateway
          uri: lb://DA-GATEWAY
          predicates:
            - Path=/gateway/**,/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    group: Gateway Service
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Iam Service
        url: iam/v3/api-docs/da-iam
      - name: Storage Service
        url: storage/v3/api-docs/da-storage
      - name: Storage Service
        url: gateway/v3/api-docs/da-gateway

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        register-health-indicator: true
        failure-rate-threshold: 50 # Circuit breaker is triggered after 50% failures
        slow-call-rate-threshold: 100
        wait-duration-in-open-state: 20s # Thời gian duy trì open
        permitted-number-of-calls-in-half-open-state: 3 #cho phép gọi 3 request call sang service 1 lần nữa thử nghiệm khi đang half open
        sliding-window-size: 3 #theo dõi 3 request để đánh giá
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 3 #cần ít nhất 10 request để đánh giá
        automatic-transition-from-open-to-half-open-enabled: true
#  timelimiter:
#    instances:
#      myCircuitBreaker:
#        timeoutDuration: 10s #specifies how long the TimeLimiter will wait for a response before timing out. In this case, if a request takes more than 10 seconds to complete, it will be canceled or failed with a timeout exception.

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: TRACE
    io.github.resilience4j: DEBUG
    org.springframework.cloud.gateway.filter.factory: TRACE
    org.springframework.web.server: DEBUG