spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  application:
    name: da-iam
    client-id: 2c7f4d5e-8c12-4f8d-b321-6e1d9e9b5f72
    client-secret: EhHKwFVOfHlMuj3CgqOBH9vAgC3xPdLH
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
        order_updates: 10
        order_inserts: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret #secret 123456
  #  sql:
  #    init:
  #      schema-locations: classpath:scheme.sql
  #      mode: always
  mail:
    registrationTemplateName: RegisterConfirmationTemplate
    passwordResetTemplateName: PasswordResetTemplate
    host: smtp.gmail.com
    port: 587
    username: tducanh157@gmail.com
    password: ospcxgltbkzykrgv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.security.keycloak.serverUrl}/realms/${application.security.keycloak.realm}
          jwk-set-uris:
            sso: ${JWK_SSO_URL:${application.security.keycloak.serverUrl}/realms/${application.security.keycloak.realm}/protocol/openid-connect/certs}
            internal: ${JWK_INTERNAL_URL:http://localhost:${server.port}/auth/certificate/.well-known/jwks.json}
          jws-algorithms: RS256
        opaquetoken:
          client-secret: ${application.security.keycloak.clientSecret}
          client-id: ${application.security.keycloak.clientId}
#
#      client:
#        registration:
#          keycloak:
#            client-id: iam-service2-client #iam-service-client-master
#            client-secret: igR8GP5MTycqAXuXbdg3wyVWW1SuygPr
#            scope: openid,profile,email
#            authorization-grant-type: authorization_code
#            redirect-uri: ${application.security.keycloak.serverUrl}
#            provider: keycloak
#        provider:
#          keycloak:
#            issuer-uri: ${application.security.keycloak.serverUrl}/realms/${application.security.keycloak.realm}

confirmation:
  registration:
    url: http://localhost:${server.port}/auth/verify-email
application:
  file:
    upload-dir: D:\\da\\images
  authProvider: DEFAULT #KEYCLOAK DEFAULT
  security:
    jwt:
      expiration: 86400000 # 1day
      refresh-token:
        expiration: 604800000 # 7days
    keycloak:
      serverUrl: http://localhost:8082
      realm: master #iam-service2-realm #master
      clientId: iam-service-client-master #iam-service2-client
      clientSecret: K9UPqjKPhmAPg3FGaKCDVvANc4Jh5dC2 #igR8GP5MTycqAXuXbdg3wyVWW1SuygPr
      grantType: password
      username: admin
      password: admin
      logoutUrl: /realms/${application.security.keycloak.realm}/protocol/openid-connect/logout
      newAccessTokenUrl: /realms/${application.security.keycloak.realm}/protocol/openid-connect/token

logging:
  file:
    path: D:\\da\\log
  level:
    org:
      springdoc: debug
      hibernate:
        sql: debug
        type:
          descriptor:
          sql: Trace
      springframework:
        security: DEBUG


server:
  port: 8081
permission:
  scopes: "READ|WRITE|DELETE|UPDATE"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





